backup-period: 12h30m12s
backup-start-message: Backup will be started
backup-finish-message: Backup finished
escape-folders:
  - CoreProtect
  - SmartBackup
escape-worlds:
  - world_the_end
backup-limit: 25
path: backups