backup-period: 1h30m12s
backup-start-message: Backup will be started
backup-finish-message: Backup finished
escape-folders:
  - CoreProtect
  - SmartBackup
escape-worlds:
  - world_the_end
path: backups